---

jwt_options:
  secret: akjdbhfkadhjf

  # refresh token expiration time in days
  refresh_expiration_time: 90
  
  # login token expiration time in hours
  login_expiration_time: 12

  # signup token expiration time in hours
  signup_expiration_time: 1

database:
  host: 127.0.0.1
  port: 5432
  username: postgres
  password: postgres
  db_name: connexxxion-backoffice
  max_connections: 80



minio:
  use_ssl: false
  endpoint: "127.0.0.1:9000"
  access_key_id: "MLAr8txZ09l14O3JPxEy"
  access_key_secret: "GCoAC7mdyXkp5RhRARqvLrp0UJHhBnETjIqIOOVq"
  

api_listen_port: 8000
log_level: info
logs_file: ./logs/cnxxxn.log
verbose: true
gin_logs: true

translations_path: ./static/translations

metrics_port: 9090